home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="home"),
]

process/urls.py
from django.urls import path
from django.views.generic import RedirectView
from . import views


app_name = "process"

urlpatterns = [
    path("get_location", views.get_location, name="get_location"),
    path("resource_parameter/<selectedParameter>/", views.resource_parameter, name="resource_parameter"), 
    path("requirement_parameter/<selectedParameter>/", views.requirement_parameter, name="requirement_parameter"), 
    path("generate_data/<selectedParameter>", views.generate_data, name="generate_data"), 
    path("create_table/<selectedParameter>", views.create_table, name="create_table"),
    path("generate_csv/<selectedParameter>", views.generate_csv, name="generate_csv"),
    path("return_process/<selectedParameter>/", views.return_process, name="return_process"),
    path("delete_table/<selectedParameter>", views.delete_table, name="delete_table"),
    path("final_report", views.final_report, name="final_report"),
    path("save_html", views.save_html, name="save_html"),
    path("", RedirectView.as_view(url="get_location")),
]

xarsed/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", include("home.urls")),
    path("process/", include("process.urls")),
    path("", RedirectView.as_view(url="home/")),
]

xarsed_WA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/", include("home.urls")),
    path("process/", include("process.urls")),
    path("", RedirectView.as_view(url="home/")),
]

process/forms.py
from django.contrib.gis import forms


class UserLocationForm(forms.Form):
    
    user_location = forms.PointField(
        label = "Your Location",
        help_text = "Select your desired location on the map below. If you want to change your selected point, press the 'Delete All Features' button at the bottom of the map.", 
        widget = forms.OSMWidget(attrs={
            "template_name": "gis/openlayers-osm.html", 
            "default_lat": 0, 
            "default_lon": 0,
            "default_zoom": 0,
    }))
    
    def save_location(self, request):

        point_object = self.cleaned_data["user_location"]
        point_srid = point_object.srid
        point_coordinates = point_object.coords
        
        if point_srid == 4326:
            time_difference = -round(point_coordinates[0] / 15)
            request.session["user_location"] = [point_coordinates[0], point_coordinates[1], time_difference]
        
        elif point_srid == 3857:
            transform_object = point_object.transform(4326, clone=True)

            if transform_object != None:
                transform_coordinates = transform_object.coords
                time_difference = -round(transform_object[0] / 15)
                request.session["user_location"] = [transform_coordinates[0], transform_coordinates[1], time_difference]

            else:
                import math
                longitude = (point_coordinates[0] * 180) / 20037508.34
                lat = (point_coordinates[1] * 180) / 20037508.34
                latitude = (math.atan(math.pow(math.e, lat * (math.pi / 180))) * 360) / math.pi - 90
                time_difference = -round(longitude / 15)
                request.session["user_location"] = [longitude, latitude, time_difference]

process/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template.loader import render_to_string
from xarsed.common.common import series_parameter, create_list, appliance_list, generate_table_list
from xarsed.solution.reporting import solar_energy_pv_electricity_battery
from xarsed.common.common import generate_list
from process.forms import UserLocationForm


def get_location(request):
    
    if request.method == "POST": 
        form = UserLocationForm(request.POST)

        if form.is_valid():
            form.save_location(request)
            
            selected_resource = "solarEnergyPV"
            series_parameters = series_parameter(selected_resource) 
            request.session["selected_resource"] = selected_resource

            request.session.set_expiry(3600)
            
            context = {"seriesParameters":series_parameters}

            return render(request, "process/get_resource.html", context)

    else:
        form = UserLocationForm()

    context = {
        "form": form,
    }

    return render(request, "process/get_location.html", context)


def resource_parameter(request, selectedParameter): 
        
    try:
        selected_resource = request.session["selected_resource"]
        series_parameters = series_parameter(selected_resource)  
        uploaded_file = request.FILES.get("uploadedFile")
        model = request.POST.get("model")

        if (uploaded_file == None and model == None):
                
            request.session.set_expiry(3600)
                
            message = "Please select at least one option!"
            context = {"message1": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
            return render(request, "process/get_resource.html", context)
            
        elif (uploaded_file != None and model != None):
                
            request.session.set_expiry(3600)
                
            message = "Please select at most one option!"
            context = {"message1": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
            return render(request, "process/get_resource.html", context)
            
        elif (uploaded_file != None and model == None):

            if uploaded_file.size > 2.5 * 1024 * 1024: #2.5MB

                request.session.set_expiry(3600)
                
                message = "Your file must be less than 2.5 MB in size!"
                context = {"message2": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
                return render(request, "process/get_resource.html", context)
                
            else:

                if (uploaded_file.name.endswith(".csv") != True or uploaded_file.content_type != "text/csv"):

                    request.session.set_expiry(3600)
                
                    message = "Your file must be in CSV format!"
                    context = {"message2": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
                    return render(request, "process/get_resource.html", context)
                    
                else:
                        
                    final_list = create_list(uploaded_file, selectedParameter)

                    if final_list == None:

                        request.session.set_expiry(3600)
                
                        message = "Please upload a file that contains only numbers and not all values ​​are zero!"
                        context = {"message2": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
                        return render(request, "process/get_resource.html", context)
                        
                    else:

                        final_length = len(final_list)

                        if final_length != 8760: #number of hours per year
                                
                            request.session.set_expiry(3600)
                
                            message = "Your data should be 8760 steps, equivalent to the number of hours in a year!"
                            context = {"message2": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
                            return render(request, "process/get_resource.html", context)
                            
                        else:

                            request.session[selectedParameter] = final_list
                            saved_parameters = []
                            for i in series_parameters:
                                try:
                                    request.session[i]
                                    saved_parameters.append(i)
                                except KeyError:
                                    continue

                            if set(series_parameters) != set(saved_parameters):
                                                                    
                                request.session.set_expiry(3600)
                
                                message = "Your data was saved successfully."
                                context = {"message4": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
                                return render(request, "process/get_resource.html", context)
                                
                            else:
                                    
                                selected_requirement = "electricity"
                                series_parameters = series_parameter(selected_requirement) 
                                request.session["selected_requirement"] = selected_requirement

                                request.session.set_expiry(3600)
                
                                context = {"seriesParameters":series_parameters} 
                                
                                return render(request, "process/get_requirement.html", context)

        elif (uploaded_file == None and model != None):
  
            latitude = request.session["user_location"][1] 
            longitude = request.session["user_location"][0]
            time_difference = request.session["user_location"][2] 

            final_list = generate_list(selectedParameter, latitude, longitude, time_difference)

            if final_list == None:
                request.session.set_expiry(3600)

                message = "The requested parameter could not be saved, please try again!"
                context = {"message3": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
                return render(request, "process/get_resource.html", context) 

            else:  
                request.session[selectedParameter] = final_list          
                
                saved_parameters = []
                for i in series_parameters:
                    try:
                        request.session[i]
                        saved_parameters.append(i)
                    except KeyError:
                        continue

                if set(series_parameters) != set(saved_parameters):
                                                                    
                    request.session.set_expiry(3600)
                            
                    message = "Your data was saved successfully."
                    context = {"message4": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
                    return render(request, "process/get_resource.html", context)
                                
                else:
                                    
                    selected_requirement = "electricity"
                    series_parameters = series_parameter(selected_requirement) 
                    request.session["selected_requirement"] = selected_requirement

                    request.session.set_expiry(3600)
                
                    context = {"seriesParameters":series_parameters} 
                                
                    return render(request, "process/get_requirement.html", context) 

    except KeyError:
        return redirect("/home/")
      

def requirement_parameter(request, selectedParameter): 

    try:
        selected_requirement = request.session["selected_requirement"]
        series_parameters = series_parameter(selected_requirement)  
        uploaded_file = request.FILES.get("uploadedFile")

        if uploaded_file.size > 2.5 * 1024 * 1024: #2.5MB

            request.session.set_expiry(3600)
                
            message = "Your file must be less than 2.5 MB in size!"
            context = {"message1": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
            return render(request, "process/get_requirement.html", context)
                
        else:

            if (uploaded_file.name.endswith(".csv") != True or uploaded_file.content_type != "text/csv"):

                request.session.set_expiry(3600)
                
                message = "Your file must be in CSV format!"
                context = {"message1": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 
                return render(request, "process/get_requirement.html", context)
                    
            else:
                        
                final_list = create_list(uploaded_file, selectedParameter)

                if final_list == None:

                    request.session.set_expiry(3600)
                
                    message = "Please upload a file that contains only numbers and not all values ​​are zero!"
                    context = {"message1": message, "seriesParameters":series_parameters, "selectedParameter":selectedParameter} 

process/templates/process/base_process.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    
    <head>
      
        <meta charset="utf-8">
      
        {% load static %}
        <link rel="shortcut icon" type="image/svg+xml" href="{% static 'images/logo.svg' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
          
        <meta name="viewport" content="width=device-width, initial-scale=1">
       
        {% block head %}
        
        {% endblock head %}
      
    </head>
      
    <body>
        
        {% block body %}
        
        {% endblock body %}

    </body>

</html>

process/templates/process/final_report.html
{% extends "process/base_process.html" %}

{% block head %}
      
    <title>Get Requirement Parameter-Xarsed</title>

    <style>

        body {
            background: radial-gradient(hsl(178.39, 91.02%, 51.96%)/*Fluorescent blue*/, hsl(8.47, 100%, 50%)/*Scarlet*/);  
        }

    </style>    

{% endblock head %}

{% block body %}

    {% for i in reportList %}
        <div class="glass">

            {{i|safe}}

        </div>
    {% endfor %}

    <div class="glass">

        <p>
            <b>Xarsed</b> hopes that this report will be useful to you and that you can take a step closer to becoming independent with the help of nature. 
            If you would like to accompany <b>Xarsed</b> on its path ahead, you can send any amount you like to the following Bitcoin address:
        </p>
        <p>
            <b id="btcAddress">{{btcAddress}}</b>
        </p>
        <button class="button" onclick="copyAddress('btcAddress')">
            Copy BTC Address
        </button>

    </div>

    <div class="glass">

        <form action="{% url 'process:save_html' %}" class="form" method="post">
            {% csrf_token %}
                
            <p>
                This report contains data, images, and interactive charts, each with a different style to highlight them. 
                If you plan to save this report, <b>Xarsed</b> recommends that you use the button below. 
                This button will prepare the report file as a single HTML file, with all its necessary materials, for your download. 
            </p>
            <p>
                Finally, you have one hour to save your report. 
                After this time, all your information will be deleted and you will need to log in again.
            </p>
            <p>
                <b>Enjoy!</b>
            </p>

            <button type="submit" class="button" id="report">Save Report</button>
        </form>

    </div>
    <div class="glass">
    
        <form action="{% url 'home:home' %}" class="form" method="get">  
            <button type="submit" class="button" id="home">Home</button>
        </form>

    </div>
    <script>

        function copyAddress(address) {

            let createInput = document.createElement("input");
            createInput.setAttribute("value", document.getElementById(address).innerHTML);
            navigator.clipboard.writeText(createInput.value);

            alert("Address copied to clipboard");

        }                      
    
    </script>

{% endblock body %}

process/templates/process/get_location.html
{% extends "process/base_process.html" %}

{% block head %}
    
    <title>Get Location-Xarsed</title>
    
    {{ form.media }}

    <link href="https://cdn.jsdelivr.net/npm/ol@v10.5.0/ol.css" media="all" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/ol@v10.5.0/dist/ol.js"></script>
    
    <style>

        body {
            background: radial-gradient(hsl(286.29, 100%, 72.55%)/*Heliotrope*/, hsl(8.82, 58.62%, 34.12%)/*Burnt umber*/);  
        }

        #id_user_location_map {
            height: 80vh; 
            width: 80vw; 
        }

        .clear_features {
            background-color: hsl(151.5, 46.51%, 83.14%); /*Aero blue*/
            border: 0.05em solid hsl(46.15, 26.53%, 90.39%); /*Alabaster*/
            border-radius: 0.5em;
            box-shadow: 0em .2em .3em hsl(204, 18.8%, 26.08%); /*Charcoal*/
            color: hsl(352.39, 67.62%, 20.59%); /*Chocolate Cosmos*/
            font-family: Verdana, Arial, sans-serif;
            font-size: 2em;
            margin: 2em;
            padding: 0.5em;
            text-shadow: 0em .05em .15em hsl(40, 5.45%, 89.22%); /*Platinum*/
            transition:  
                box-shadow 0.1s,
                color 0.2s,
                font-weight 0.3s,
                font-size 0.3s;
        }

        .clear_features:hover, .clear_features:focus {
            box-shadow: 0em .1em .3em hsl(204, 18.8%, 26.08%); /*Charcoal*/
            font-weight: bold;
            font-size: 2.5em;
        } 

        .clear_features:active {
            box-shadow: 0em .1em .3em hsl(204, 18.8%, 26.08%); /*Charcoal*/
            font-weight: bold;
            font-size: 2.5em;
        }
    
    </style>

{% endblock head %}

{% block body %}

    <div class="glass">

        <h1>
            Get your location for potential assessment
        </h1>
        <p>
            For solar radiation calculations, you need to determine the desired location where you want to run your solar plant.
        </p>
        
    </div>

    <div class="glass">
        
        <form action="{% url 'process:get_location' %}" class="form" method="post">            
            {% csrf_token %}
            
            {{ form.user_location.label_tag }}
            <p>
                {{ form.user_location.help_text }}
            </p> 
            <div class="message">
                {{ form.non_field_errors.as_text }}
                {{ form.user_location.errors.as_text }}
            </div>
            {{ form.user_location }}

            <button type="submit" class="button" id="getLocation">Send</button>

        </form>
    
    </div>

{% endblock body %}

process/templates/process/get_requirement.html
{% extends "process/base_process.html" %}

{% block head %}
    
    <title>Get Requirement Parameter-Xarsed</title>

    {% load process_function %}
    
    <style>

        body {
            background: radial-gradient(hsl(336, 35.29%, 66.67%)/*Rose Gold*/, hsl(160.91, 34.02%, 38.04%)/*Viridian*/);  
        }
    
    </style>    

{% endblock head %}

{% block body %}

    <div class="glass">

        <h1>
            Get your data for requirement parameter
        </h1>
        <p>
            Here you just need to set the electricity parameter. Again, there are two ways to do this: 
            Either enter your hourly consumption data or create this data using the <b>Generate Data</b> tool. 
            Your file should contain 8760 positive or zero numbers, as in the previous section. 
            The important thing here is that these values ​​should be the aggregate (not the average) of your electricity consumption per hour and in watts.
        </p>
            
    </div>

    {% for i in seriesParameters %}
        
        <div class="glass">

            <form action="{% url 'process:requirement_parameter' i %}" class="form" id="{{i}}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                
                <h2>
                    {{i|replace_underscore}}
                </h2>
                
                <label for="uploadedFile">Upload your file:<br>(the uploaded file must be in CSV format and less than 2.5 MB in size)</label>
                <input type="file" class="input" id="uploadedFile" name="uploadedFile" accept=".csv" required />

                {% if i == selectedParameter %}
                <div class="message">
                    {{message1}}
                </div>
                {% else %}
                <div></div>
                {% endif %}

                <button type="submit" class="button" id="uploadedFile">Send</button>

                {% if i == selectedParameter %}
                <div class="message">
                    {{message2}}
                </div>
                {% else %}
                <div></div>
                {% endif %}

            </form>
            <form action="{% url 'process:generate_data' i %}" class="form" method="post">
                {% csrf_token %}

                <p>
                    If you don't have data for the {{i|replace_underscore}} parameter, you can use the <b>Generate Data</b> tool to generate a time series for the desired parameter:
                </p>
                
                <button type="submit" class="button" id="generateData" style="font-size: 2em;">Generate Data</button>

            </form>

        </div>

    {% endfor %} 

    <script>

        let url = window.location.pathname;

        let segments = url.split("/");

        let lastSegment = segments[segments.length - 2];

        if (lastSegment != "process"){
            segments[segments.length-1] = "#" + lastSegment;
            let newPath = segments.join("/");
            window.location.href = newPath;
        }
        else {
            // do nothing
        }

    </script>

{% endblock body %}

process/templates/process/get_resource.html
{% extends "process/base_process.html" %}

{% block head %}
    
    <title>Get Resource Parameter-Xarsed</title>

    {% load process_function %}
    
    <style>

        body {
            background: radial-gradient(hsl(80.24, 100%, 49.41%)/*Spring Bud*/, hsl(344.21, 100%, 37.25%)/*Apple red*/);  
        }
    
    </style>    

{% endblock head %}

{% block body %}

    <div class="glass">

        <h1>
            Get your data for resource parameters
        </h1>
        <p>
            To perform solar calculations, there are four essential environmental parameters that need to be determined. 
            You have two ways to do this: provide your own data or ask <b>Xarsed</b> to generate average data for your location. 
            For the second method, simply check the box for <b>Get data from models</b> and submit the form 
            (just note that these are simplified and approximate values, so they may differ from the actual values),
            but for the first method, you need to pay attention to the following points:
        </p>
        <ul>
            <li>
                You need to provide a file containing a column with 8760 rows containing the value of hourly averages for a period of one year. (24 hours in 365 days).
            </li>
            <li>
                No header is required and no non-numeric characters are acceptable.
            </li>
            <li>
                For the temperature parameter, you need to provide the ambient temperature, preferably at a height of two meters, in Kelvin.
            </li>
            <li>
                For the second and third parameters, which are related to solar flux, you need to provide the surface flux in watts per square meter.
            </li>
            <li>
                For the albedo parameter, you need to provide the surface albedo with values ​​between 0 and 1 and without units.
            </li>
        </ul>
        <p>
            Given these points, negative values ​​are not acceptable for any of them and will automatically be converted to zero.
        </p>
        <p>
            <b>
                The final point is to do this for each parameter separately because only the form whose submit button you pressed will receive the data.
            </b>
        </p>
            
    </div>

    {% for i in seriesParameters %}
        
        <div class="glass">

            <form action="{% url 'process:resource_parameter' i %}" class="form" id="{{i}}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
            
                <h2>
                    {{i|replace_underscore}}
                </h2>

                {% if i == selectedParameter %}
                <div class="message">
                    {{message1}}
                </div>
                {% else %}
                <div></div>
                {% endif %}
                
                <label for="uploadedFile">Upload your file:<br>(the uploaded file must be in CSV format and less than 2.5 MB in size)</label>
                <input type="file" class="input" id="uploadedFile" name="uploadedFile" accept=".csv" />

                {% if i == selectedParameter %}
                <div class="message">
                    {{message2}}
                </div>
                {% else %}
                <div></div>
                {% endif %}

                <label for="model">Get data from models:<br>(This data is the result of statistical and machine learning models trained with satellite data)</label>
                <input type="checkbox" class="input" id="model" name="model" value="model">

                {% if i == selectedParameter %}
                <div class="message">
                    {{message3}}
                </div>
                {% else %}
                <div></div>
                {% endif %}

                <button type="submit" class="button" id="uploadedFile">Send</button>

                {% if i == selectedParameter %}
                <div class="message">
                    {{message4}}
                </div>
                {% else %}
                <div></div>
                {% endif %}

            </form>

        </div>

    {% endfor %} 

    <script>

        let url = window.location.pathname;

        let segments = url.split("/");

        let lastSegment = segments[segments.length - 2];

        if (lastSegment != "process"){
            segments[segments.length-1] = "#" + lastSegment;
            let newPath = segments.join("/");
            window.location.href = newPath;
        }
        else {
            // do nothing
        }

    </script>

{% endblock body %}